name: marp-to-pages
concurrency: marp-to-pages
permissions:
  contents: write
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy images
        run: mkdir build && cp -R img build/img

      - name: Marp Build (index)
        uses: docker://marpteam/marp-cli:latest
        with:
          args: presentation.md --html -o build/index.html
        env:
          MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
